Add unit tests for org.springframework.security.oauth2.common.exceptions.OAuth2Exception
Diffblue-benchmarks/Spring-projects-spring-security-oauth pull request #2
Opened 2019-08-07 13:00 UTC by ThomasPerkins1123

These tests were written using Diffblue Cover.

2019-08-07 14:20 UTC, JohnLBergqvist requested changes
You've used `test` in the method names twice.

2019-08-08 09:40 UTC, ThomasPerkins1123 commented
> You've used `test` in the method names twice.

Sorry I did fix this but forgot to push! Is fixed now

2019-08-08 12:11 UTC, JohnLBergqvist requested changes

2019-08-08 12:11 UTC, JohnLBergqvist commented on spring-security-oauth2/src/test/java/org/springframework/security/oauth2/common/exceptions/OAuth2ExceptionTest.java
> +                        oAuth2Exception.getMessage());
Does this need to be on a 2nd line?

2019-08-08 12:11 UTC, JohnLBergqvist commented on spring-security-oauth2/src/test/java/org/springframework/security/oauth2/common/exceptions/OAuth2ExceptionTest.java
> +                        oAuth2Exception.getMessage());
Same as above

2019-08-08 12:11 UTC, JohnLBergqvist commented on spring-security-oauth2/src/test/java/org/springframework/security/oauth2/common/exceptions/OAuth2ExceptionTest.java
> +                        oAuth2Exception.getMessage());
Same as above

2019-08-09 09:00 UTC, JohnLBergqvist approved these changes

2019-08-09 14:11 UTC, petersear approved these changes

2019-09-04 08:50 UTC, closed without merging